name: "Repo clone"

on:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone supercharge website repository
        uses: actions/checkout@v2
        with:
          path: newfile.json
          repository: supercharge/docs
      - name: Access cloned repository content
        run: |
          cd: newfile.json
          pwd
          ls -la
